/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */

export type CodePushUpdateAllOf = {
  download_url: string;
  is_available: boolean;
  package_size: number;
  should_run_binary_version: boolean;
  target_binary_range: string;
  update_app_version: boolean;
};
