/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */
import type { CodePushPackageInfo } from "./codePushPackageInfo";
import type { CodePushUpdateAllOf } from "./codePushUpdateAllOf";

export type CodePushUpdate = CodePushPackageInfo & CodePushUpdateAllOf;
