/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */

export type CodePushPackageInfo = {
  app_version: string;
  description?: string;
  is_disabled?: boolean;
  is_mandatory: boolean;
  label: string;
  package_hash: string;
  rollout?: number;
};
