/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */
import type { CodePushUpdate } from "./codePushUpdate";

export type GetCodePushUpdate200 = {
  update_info: CodePushUpdate;
};
