/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */

export type GetCodePushUpdateParams = {
  app_version: string;
  deployment_key: string;
  package_hash?: string;
  is_companion?: boolean;
  client_unique_id?: string;
};
