/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateStatus } from "./updateStatus";

export type GetUpdatesParams = {
  /**
   * Filter updates by status
   */
  status?: UpdateStatus;
  /**
   * Filter updates by runtime version
   */
  runtimeVersion?: string;
  /**
   * Filter updates by channel
   */
  channel?: string;
};
