/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */
import type { StorageObjectPathWithURL } from "./storageObjectPathWithURL";

export type PrepareUpdateResponse = {
  updateID: string;
  uploadURLs: StorageObjectPathWithURL[];
};
