/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */
import type { PrepareUpdateBodyExpoAppConfig } from "./prepareUpdateBodyExpoAppConfig";
import type { StorageObject } from "./storageObject";

export type PrepareUpdateBody = {
  channel?: string;
  expoAppConfig?: PrepareUpdateBodyExpoAppConfig;
  fileMetadata: StorageObject[];
  message: string;
  runtimeVersion: string;
};
