/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */

export type StorageObject = {
  contentLength: number;
  contentType: string;
  extension: string;
  md5Hash: string;
  path: string;
};
