/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */

export type UpdateProtocol =
  (typeof UpdateProtocol)[keyof typeof UpdateProtocol];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateProtocol = {
  expo: "expo",
  codepush: "codepush",
} as const;
