/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationFieldError } from "./validationFieldError";

export type ValidationErrors = {
  errors: ValidationFieldError[];
};
