/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Paratrooper API
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationErrorItem } from "./validationErrorItem";

export type ValidationError = {
  errors: ValidationErrorItem[];
};
